spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/postgres
#    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: true
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            tablePrefix: QRTZ_
#            dataSource: hikari

