version: "3.9"
services:
  postgresql:
    image: postgres:13.2
    container_name: postgresql
    restart: always
    ports:
#      remove line below if you don't want to work with db manually
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 123

  service:
    image: payoneer/job-service:1.0
    container_name: service
    ports:
      - "8080:8080"
    environment:
#      remove line below if UTC timezone is OK for you
      - "CATALINA_OPTS=-Duser.timezone=Europe/Moscow"
    depends_on:
      - postgresql


#  mail server
#    etc

volumes:
  pgdata: